package com.tvo.puzzle.entity;
// default package
// Generated Jul 16, 2013 4:38:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMember generated by hbm2java
 */
@Entity
@Table(name = "tbl_member", catalog = "puzzle")
public class Member implements java.io.Serializable {

	private Integer id;
	private String udid;
	private Date registerDate;
	private String userAgent;
	private int currentPoint;
	private Set<PresentManagement> presentManagements = new HashSet<PresentManagement>(
			0);
	private Set<PointManagement> tblPointManagements = new HashSet<PointManagement>(
			0);

	public Member() {
	}

	public Member(String udid, Date registerDate, String userAgent,
			int currentPoint) {
		this.udid = udid;
		this.registerDate = registerDate;
		this.userAgent = userAgent;
		this.currentPoint = currentPoint;
	}

	public Member(String udid, Date registerDate, String userAgent,
			int currentPoint, Set<PresentManagement> presentManagements,
			Set<PointManagement> tblPointManagements) {
		this.udid = udid;
		this.registerDate = registerDate;
		this.userAgent = userAgent;
		this.currentPoint = currentPoint;
		this.presentManagements = presentManagements;
		this.tblPointManagements = tblPointManagements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "udid", nullable = false, length = 45)
	public String getUdid() {
		return this.udid;
	}

	public void setUdid(String udid) {
		this.udid = udid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@Column(name = "user_agent", nullable = false, length = 45)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Column(name = "current_point", nullable = false)
	public int getCurrentPoint() {
		return this.currentPoint;
	}

	public void setCurrentPoint(int currentPoint) {
		this.currentPoint = currentPoint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblMember")
	public Set<PresentManagement> getPresentManagements() {
		return this.presentManagements;
	}

	public void setPresentManagements(Set<PresentManagement> presentManagements) {
		this.presentManagements = presentManagements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblMember")
	public Set<PointManagement> getTblPointManagements() {
		return this.tblPointManagements;
	}

	public void setTblPointManagements(
			Set<PointManagement> tblPointManagements) {
		this.tblPointManagements = tblPointManagements;
	}

}
