package com.tvo.puzzle.entity;

// Generated Sep 11, 2012 3:13:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_role")
public class Role implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Set<UserRole> tblUserRoles = new HashSet<UserRole>(0);

	public Role() {
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(String roleName, Set<UserRole> tblUserRoles) {
		this.roleName = roleName;
		this.tblUserRoles = tblUserRoles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "role_name", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRole")
	public Set<UserRole> getTblUserRoles() {
		return this.tblUserRoles;
	}

	public void setTblUserRoles(Set<UserRole> tblUserRoles) {
		this.tblUserRoles = tblUserRoles;
	}

}
