package com.tvo.puzzle.entity;

// Generated Sep 11, 2012 3:13:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblSession generated by hbm2java
 */
@Entity
@Table(name = "tbl_session")
public class Session implements java.io.Serializable {

	private Integer id;
	private int playerId;
	private String sessionId;

	public Session() {
	}

	public Session(int playerId, String sessionId) {
		this.playerId = playerId;
		this.sessionId = sessionId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "player_id", nullable = false)
	public int getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(int playerId) {
		this.playerId = playerId;
	}

	@Column(name = "session_id", nullable = false, length = 45)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

}
