package com.tvo.puzzle.entity;

// Generated Sep 27, 2012 1:53:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUserRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_role")
public class UserRole implements java.io.Serializable {

	private Integer id;
	private User tblUser;
	private Role tblRole;

	public UserRole() {
	}

	public UserRole(User tblUser, Role tblRole) {
		this.tblUser = tblUser;
		this.tblRole = tblRole;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public User getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(User tblUser) {
		this.tblUser = tblUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getTblRole() {
		return this.tblRole;
	}

	public void setTblRole(Role tblRole) {
		this.tblRole = tblRole;
	}

}
