package com.tvo.puzzle.entity;

// Generated Sep 27, 2012 1:53:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.ForeignKey;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user")
public class User implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private List<Role> lsRole;
	
	@ManyToMany(fetch = FetchType.EAGER, targetEntity = Role.class, cascade = {
		CascadeType.PERSIST, CascadeType.MERGE })
	@ForeignKey(name = "fk_user_role_user", inverseName = "fk_user_role_role")
	@JoinTable(name = "tbl_user_role", joinColumns = { @JoinColumn(name = "user_id"), }, inverseJoinColumns = { @JoinColumn(name = "role_id") })
	@Fetch(FetchMode.SELECT)
	public List<Role> getLsRole() {
		return lsRole;
	}

	public void setLsRole(List<Role> lsRole) {
		this.lsRole = lsRole;
	}

	private Set<UserRole> tblUserRoles = new HashSet<UserRole>(0);

	public User() {
	}

	public User(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public User(String userName, String password,
			Set<UserRole> tblUserRoles) {
		this.userName = userName;
		this.password = password;
		this.tblUserRoles = tblUserRoles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblUser")
	public Set<UserRole> getTblUserRoles() {
		return this.tblUserRoles;
	}

	public void setTblUserRoles(Set<UserRole> tblUserRoles) {
		this.tblUserRoles = tblUserRoles;
	}

}
