package com.tvo.puzzle.entity;
// default package
// Generated Jul 16, 2013 4:38:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblGameDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_game_detail", catalog = "puzzle")
public class GameDetail implements java.io.Serializable {

	private Integer id;
	private Game tblGame;
	private String resource;
	private String folderName;


	public GameDetail() {
	}

	public GameDetail(Game tblGame, String resource,String folderName) {
		this.tblGame = tblGame;
		this.resource = resource;
		this.folderName = folderName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "game_id", nullable = false)
	public Game getTblGame() {
		return this.tblGame;
	}

	public void setTblGame(Game tblGame) {
		this.tblGame = tblGame;
	}

	@Column(name = "resource", nullable = false, length = 256)
	public String getResource() {
		return this.resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}
	
	@Column(name = "folderName", nullable = false, length = 50)
	public String getFolderName() {
		return folderName;
	}

	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}
}
