package com.tvo.puzzle.entity;
// default package
// Generated Jul 16, 2013 4:38:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPointManagement generated by hbm2java
 */
@Entity
@Table(name = "tbl_point_management", catalog = "puzzle")
public class PointManagement implements java.io.Serializable {

	private Integer id;
	private Project tblProject;
	private Member tblMember;
	private Date createdDate;
	private int pointValue;
	private String code;

	public PointManagement() {
	}


	public PointManagement(Member tblMember, Date createdDate, int pointValue, String code) {
		this.tblMember = tblMember;
		this.createdDate = createdDate;
		this.pointValue = pointValue;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getTblMember() {
		return this.tblMember;
	}

	public void setTblMember(Member tblMember) {
		this.tblMember = tblMember;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "point_value", nullable = false)
	public int getPointValue() {
		return this.pointValue;
	}

	public void setPointValue(int pointValue) {
		this.pointValue = pointValue;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getTblProject() {
		return tblProject;
	}


	public void setTblProject(Project tblProject) {
		this.tblProject = tblProject;
	}

}
