package com.tvo.puzzle.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PresentManagement generated by hbm2java
 */
@Entity
@Table(name = "tbl_present_management", catalog = "puzzle")
public class PresentManagement implements java.io.Serializable {

	private Integer id;
	private Member tblMember;
	private Product tblProduct;
	private Date registerDate;
	private String memberName;
	private String postalCode;
	private String address;
	private String phoneNumber;
	private String mailAddress;
	private boolean gender;
	private String message;

	public PresentManagement() {
	}

	public PresentManagement(Member tblMember, Product tblProduct,
			Date registerDate, String memberName,
			String postalCode, String address, String phoneNumber,
			String mailAddress, boolean gender, String message) {
		this.tblMember = tblMember;
		this.tblProduct = tblProduct;
		this.registerDate = registerDate;
		this.memberName = memberName;
		this.postalCode = postalCode;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.mailAddress = mailAddress;
		this.gender = gender;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getTblMember() {
		return this.tblMember;
	}

	public void setTblMember(Member tblMember) {
		this.tblMember = tblMember;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getTblProduct() {
		return this.tblProduct;
	}

	public void setTblProduct(Product tblProduct) {
		this.tblProduct = tblProduct;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@Column(name = "member_name", nullable = false, length = 45)
	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	@Column(name = "postal_code", nullable = false, length = 45)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "address", nullable = false, length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_number", nullable = false, length = 16)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "mail_address", nullable = false, length = 128)
	public String getMailAddress() {
		return this.mailAddress;
	}

	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	@Column(name = "gender", nullable = false,length=20)
	public boolean getGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

	@Column(name = "message", nullable = false, length = 1024)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
