package com.tvo.puzzle.entity;
// default package
// Generated Jul 16, 2013 4:38:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProduct generated by hbm2java
 */
@Entity
@Table(name = "tbl_product", catalog = "puzzle")
public class Product implements java.io.Serializable {

	private Integer id;
	private Project tblProject;
	private String productCode;
	private String productName;
	private Date createDate;
	private int requiredPoint;
	private Date startTime;
	private Date endTime;
	private boolean valid;
	private Set<PresentManagement> presentManagements = new HashSet<PresentManagement>(
			0);

	public Product() {
	}

	public Product(String productCode, String productName, Date createDate,
			int requiredPoint, Date startTime, Date endTime, boolean valid) {
		this.productCode = productCode;
		this.productName = productName;
		this.createDate = createDate;
		this.requiredPoint = requiredPoint;
		this.startTime = startTime;
		this.endTime = endTime;
		this.valid = valid;
	}

	public Product(String productCode, String productName, Date createDate,
			int requiredPoint, Date startTime, Date endTime, boolean valid,
			Set<PresentManagement> presentManagements) {
		this.productCode = productCode;
		this.productName = productName;
		this.createDate = createDate;
		this.requiredPoint = requiredPoint;
		this.startTime = startTime;
		this.endTime = endTime;
		this.valid = valid;
		this.presentManagements = presentManagements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getTblProject() {
		return tblProject;
	}

	public void setTblProject(Project tblProject) {
		this.tblProject = tblProject;
	}

	@Column(name = "product_code", nullable = false, length = 45)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "product_name", nullable = false, length = 256)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "required_point", nullable = false)
	public int getRequiredPoint() {
		return this.requiredPoint;
	}

	public void setRequiredPoint(int requiredPoint) {
		this.requiredPoint = requiredPoint;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "valid", nullable = false)
	public boolean getValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProduct")
	public Set<PresentManagement> getPresentManagements() {
		return this.presentManagements;
	}

	public void setPresentManagements(Set<PresentManagement> presentManagements) {
		this.presentManagements = presentManagements;
	}

}
